name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Autopilot fails to commit when...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'autopilot start'
        2. Edit 'foo.js'
        3. See error...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Autopilot Version
      description: What version of autopilot-cli are you using? (Run `autopilot -v`)
      placeholder: v0.1.7
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using? (Run `node -v`)
      placeholder: v18.16.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on?
      placeholder: Windows 11, macOS Sonoma, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Please copy and paste any relevant logs from `autopilot.log` or the terminal.
      render: shell
